name: CMake

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: true
          install: >
            git
            mingw-w64-x86_64-git-lfs
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-asio

      - name: Git LFS Setup
        run: |
          /mingw64/bin/git-lfs install
          cp /mingw64/bin/git-lfs /usr/bin/
          git lfs install

      - name: Download NSIS
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://altushost-swe.dl.sourceforge.net/project/nsis/NSIS%203/3.12/nsis-3.12.zip?viasf=1&fid=f22debbde4014ca0" `
            -OutFile nsis.zip

          Expand-Archive nsis.zip -DestinationPath "$PWD\nsis"

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}

      # - name: Cache Discord SDK
      #   uses: actions/cache@v4
      #   with:
      #     path: lib/discord_social_sdk
      #     key: discord-sdk-v1

      - name: Clone Discord SDK repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/immails/discord_social_sdk.git lib/discord_social_sdk

      - name: Configure CMake
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DAPP_VERSION=$VERSION

      - name: Build
        run: cmake --build build

      # - name: Collect artifacts
      #   shell: bash
      #   run: |
      #     mkdir -p package

      #     cp -r build/bin/* package/ || true

      - name: Make installer
        shell: pwsh
        run: |
          & "$PWD\nsis\nsis-3.12\makensis.exe" installer.nsi

      - name: Create archive
        shell: msys2 {0}
        run: |
          cd ./build/bin/
          zip -r ../../WebRichPresencePortable.zip ./*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: WebRichPresencePortable.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            WebRichPresenceSetup.exe
            WebRichPresencePortable.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}