name: CMake

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: true
          install: >
            git
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-asio

      - name: Install NSIS
        shell: pwsh
        run: |
          choco install nsis -y

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}

      # - name: Cache Discord SDK
      #   uses: actions/cache@v4
      #   with:
      #     path: lib/discord_social_sdk
      #     key: discord-sdk-v1

      - name: Clone Discord SDK repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/immails/discord_social_sdk.git lib/discord_social_sdk

      - name: Configure CMake
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DAPP_VERSION=$VERSION

      - name: Build
        run: cmake --build build

      # - name: Collect artifacts
      #   shell: bash
      #   run: |
      #     mkdir -p package

      #     cp -r build/bin/* package/ || true

      - name: Make installer
        shell: pwsh
        run: |
          makensis installer.nsi

      - name: Create archive
        shell: msys2 {0}
        run: |
          zip -r ./release.zip ./build/bin/*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: release.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            WebRichPresenceSetup.exe
            release.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}